### ISSUE TITLE
Conversion not accurate

### ISSUE THREAD

**Issue by leongwq** [cgcai/SVY21#5]
Converting X,Y from onemap is totally off.

Using the script calculates wrong coordinates from :
http://www.onemap.sg/api/help/HTMLSource/ConvertCords.aspx

**Comment by khankuan** [comment]
Hey, is there a sample input point. Just one thing I noticed, the inputs for onemap is long,lat while the library is lat,long.

**Comment by jonongjs** [comment]
@leongwq, how off is "totally off"? Using the sample point on onemap and a few reference points in our test cases, the errors between onemap and our library are less than 0.01%. Could it be a case of ordering the lat/lon (or northing/easting) wrongly?
